name: Auto add iteration

description: Automatically add iteration.
author: mavi0
branding:
  icon: calendar
  color: blue

inputs:
  owner:
    description: The account name of the GitHub organization.
    required: true
  number:
    description: Project number as you see it in the URL of the project.
    required: true
  token:
    description: Personal access token or an OAuth token. the write:org scope is required for read-write access.
    required: true
  iteration-field:
    description: The name of your iteration field.
    required: true
  new-iteration:
    description: Should be current or next.
    required: true
  default-status:
    description: Default status to assign to items without a status.
    required: true

runs:
  using: node20
  main: dist/index.js